name: Debian Build

on:
  workflow_run:
    workflows:
      - Linux Build
    types:
      - completed

jobs:
  build_android:
    name: Build Debian
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make Debian
      run: |
        rm -rf debian/strlen.deb 2>/dev/null
        rm -rf debian/strlen/usr/bin/strlen 2>/dev/null
        cp -f release/strlen debian/strlen/usr/bin/strlen
        cd debian
        dpkg-deb --build strlen
        cd ../
        strlen_debian_md5_text='{\n\t"schemaVersion": 1,\n\t"color": "2E9778",\n\t"label": "strlen.deb MD5",\n\t"message": "PLACEHOLDER",\n\t"labelColor": "1d1d1d",\n\t"style": "for-the-badge",\n\t"namedLogo": "debian"\n}'
        if ! [[ -d "docs/json" ]]; then
          mkdir -p docs/json
        fi
        if ! [[ -f "docs/json/strlen_debian_md5.json" ]]; then
          touch docs/json/strlen_debian_md5.json
        fi
        echo -e "$strlen_debian_md5_text" > docs/json/strlen_debian_md5.json
        sed -i "s/\"message\": \".*\"/\"message\": \"$(md5sum debian/strlen.deb | cut -d' ' -f 1)\"/g" docs/json/strlen_debian_md5.json
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Built Debian
        add_options: '--force'
        push_options: '--force'
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        tag: 1.0.0
        name: Stable Release
        prerelease: False
        artifacts: "debian/strlen.deb"
        token: ${{ secrets.GITHUB_TOKEN }}
