name: Windows Build

on:
  workflow_run:
    workflows:
      - Android Build
    types:
      - completed

jobs:

  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.0.2
      - name: Make Windows
        run: |
          Remove-Item -Path '.\source\strlen\source\Build\x86\strlen-x86.exe' -ErrorAction SilentlyContinue
          Remove-Item -Path '.\source\strlen\source\Build\x64\strlen-x64.exe' -ErrorAction SilentlyContinue
          msbuild "source\strlen.sln" /p:OutDir="source\Build\x86\" /p:Configuration=Release /p:Platform=x86
          Move-Item -Path '.\source\strlen\source\Build\x86\strlen.exe' -Destination '.\source\strlen\source\Build\x86\strlen-x86.exe'
          msbuild "source\strlen.sln" /p:OutDir="source\Build\x64\" /p:Configuration=Release /p:Platform=x64
          Move-Item -Path '.\source\strlen\source\Build\x64\strlen.exe' -Destination '.\source\strlen\source\Build\x64\strlen-x64.exe'
          Remove-Item -Force -Path '.\source\strlen\Release\strlen.iobj' -ErrorAction SilentlyContinue
          Remove-Item -Force -Path '.\source\strlen\Release\strlen.ipdb' -ErrorAction SilentlyContinue
          Remove-Item -Force -Path '.\source\strlen\Release\strlen.obj' -ErrorAction SilentlyContinue
          Remove-Item -Force -Path '.\source\strlen\Release\strlen.tlog\link.write.1.tlog' -ErrorAction SilentlyContinue
          Remove-Item -Force -Path '.\source\strlen\Release\vc142.pdb' -ErrorAction SilentlyContinue
          Remove-Item -Force -Path '.\source\strlen\source\Build\x64\strlen.pdb' -ErrorAction SilentlyContinue
          Remove-Item -Force -Path '.\source\strlen\source\Build\x86\strlen.pdb' -ErrorAction SilentlyContinue
          Remove-Item -Force -Path '.\source\strlen\x64\Release\strlen.iobj' -ErrorAction SilentlyContinue
          Remove-Item -Force -Path '.\source\strlen\x64\Release\strlen.ipdb' -ErrorAction SilentlyContinue
          Remove-Item -Force -Path '.\source\strlen\x64\Release\strlen.tlog\link.write.1.tlog' -ErrorAction SilentlyContinue
          $strlen_x86_md5_text = @'
          {
            "schemaVersion": 1,
            "color": "2E9778",
            "label": "strlen-x86.exe MD5",
            "message": "PLACEHOLDER",
            "labelColor": "1d1d1d",
            "style": "for-the-badge",
            "namedLogo": "windows"
          }
          '@
          New-Item -ItemType Directory -Force -Path '.\docs\json'
          Write-Output "$strlen_x86_md5_text" > .\docs\json\strlen_x86_md5.json
          $file = ".\docs\json\strlen_x86_md5.json"
          $md5 = New-Object -TypeName System.Security.Cryptography.MD5CryptoServiceProvider
          $hash = [System.BitConverter]::ToString($md5.ComputeHash([System.IO.File]::ReadAllBytes("source/strlen/source/Build/x86/strlen-x86.exe")))
          ((Get-Content -path $file -Raw) -replace 'PLACEHOLDER',$hash) | Set-Content -Path "$file"
          $strlen_x64_md5_text = @'
          {
            "schemaVersion": 1,
            "color": "2E9778",
            "label": "strlen-x64.exe MD5",
            "message": "PLACEHOLDER",
            "labelColor": "1d1d1d",
            "style": "for-the-badge",
            "namedLogo": "windows"
          }
          '@
          Write-Output "$strlen_x64_md5_text" > .\docs\json\strlen_x64_md5.json
          $file = ".\docs\json\strlen_x64_md5.json"
          $md5 = New-Object -TypeName System.Security.Cryptography.MD5CryptoServiceProvider
          $hash = [System.BitConverter]::ToString($md5.ComputeHash([System.IO.File]::ReadAllBytes("source/strlen/source/Build/x64/strlen-x64.exe")))
          ((Get-Content -path $file -Raw) -replace 'PLACEHOLDER',$hash) | Set-Content -Path "$file"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Built Windows
          add_options: '--force'
          push_options: '--force'
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: True
          tag: 1.0.0
          name: Stable Release
          prerelease: False
          artifacts: "source\\strlen\\source\\Build\\x86\\strlen-x86.exe,source\\strlen\\source\\Build\\x64\\strlen-x64.exe"
          token: ${{ secrets.GITHUB_TOKEN }}